---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/disks/solr
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: solr-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi